-- [Rare Source] Supabase Setup SQL

-- 1. Create the search_history table
create table public.search_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  query text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.search_history enable row level security;

-- 3. Create a policy to allow anyone (anon) to insert and read
-- (For a real production app, you would restrict this to authenticated users)
create policy "Enable read access for all users"
on public.search_history for select
using (true);

create policy "Enable insert access for all users"
on public.search_history for insert
with check (true);
